FROM node:18 as build

# Çalışma dizinini ayarla
WORKDIR /app

# package.json ve package-lock.json dosyalarını kopyala
COPY ./client/package*.json ./

# Bağımlılıkları yükle
RUN npm install

# Kaynak kodları kopyala
COPY ./client ./

# Build al
RUN npm run build

# Nginx aşaması - üretim ortamı için
FROM nginx:alpine

# React build çıktısını Nginx'e kopyala
COPY --from=build /app/build /usr/share/nginx/html

# Nginx yapılandırmasını kopyala
COPY ./docker/nginx/react.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]